FROM golang:1.22.1-alpine AS builder
WORKDIR /backend
COPY ./app ./app
COPY go.mod go.sum ./
RUN go mod download
RUN go build -o /main ./app/cmd


FROM alpine:latest
COPY --from=builder /main /bin/main
EXPOSE 8000
CMD ["/bin/main"]